### PR TITLE
Code review + Improvement

### PR DESCRIPTION
**Pull request by Ekristoffe**
Add ; at the end of the line.
Change ' into " for strings.
Check the settings in the html file.
Set the default priority to 16.

### CODE REVIEW

**Comment by biancode** [comment]
@Ekristoffe I cannot accept this PR because it violates the CONTRIBUTION rules and makes format changes that are undesirable.

**Comment by biancode** [comment]
It uses standard.js - please use the npm scripts to test and lint the code! ;)

**Comment by biancode** [comment]
see [CONTRIBUTING.md ](https://github.com/BiancoRoyal/node-red-contrib-bacnet/blob/master/.github/CONTRIBUTING.md)

**Comment by Ekristoffe** [comment]
funny that you use standard.js (single quote and other) but the automatic code review give error on it.
Maybe configure the automatic code review ?
I will roll it back to the standard.js system

**Comment by Ekristoffe** [comment]
I will make a cleaner one, in the mean time I close this one.

**Pull request closed without merging**
